// <auto-generated />
using System;
using FocusMapApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FocusMapApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829165507_AddPasswordHashAndAdminRole")]
    partial class AddPasswordHashAndAdminRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FocusMapApi.Models.AudioDescriptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndOfAudio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_of_audio");

                    b.Property<Guid?>("InterestPointId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_point_of_interest");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartOfAudio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_of_audio");

                    b.HasKey("Id");

                    b.HasIndex("InterestPointId");

                    b.HasIndex("SessionId");

                    b.ToTable("audio_description");
                });

            modelBuilder.Entity("FocusMapApi.Models.InterestPointModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("points_of_interest");
                });

            modelBuilder.Entity("FocusMapApi.Models.SessionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AttentionValue")
                        .HasColumnType("integer")
                        .HasColumnName("attention_value");

                    b.Property<int?>("DeltaPower")
                        .HasColumnType("integer")
                        .HasColumnName("delta_power");

                    b.Property<int?>("HighAlphaPower")
                        .HasColumnType("integer")
                        .HasColumnName("high_alpha_power");

                    b.Property<int?>("HighBetaPower")
                        .HasColumnType("integer")
                        .HasColumnName("high_beta_power");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("LowAlphaPower")
                        .HasColumnType("integer")
                        .HasColumnName("low_alpha_power");

                    b.Property<int?>("LowBetaPower")
                        .HasColumnType("integer")
                        .HasColumnName("low_beta_power");

                    b.Property<int?>("LowGammaPower")
                        .HasColumnType("integer")
                        .HasColumnName("low_gamma_power");

                    b.Property<int?>("MeditationValue")
                        .HasColumnType("integer")
                        .HasColumnName("meditation_value");

                    b.Property<int?>("MiddleGammaPower")
                        .HasColumnType("integer")
                        .HasColumnName("middle_gamma_power");

                    b.Property<int?>("RawEegValue")
                        .HasColumnType("integer")
                        .HasColumnName("raw_eeg_value");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int?>("ThetaPower")
                        .HasColumnType("integer")
                        .HasColumnName("theta_power");

                    b.Property<DateTime>("TimestampOfRecord")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_of_record");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TimestampOfRecord");

                    b.ToTable("session_data");
                });

            modelBuilder.Entity("FocusMapApi.Models.SessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PoorSignal")
                        .HasColumnType("integer")
                        .HasColumnName("poor_signal");

                    b.Property<DateTime?>("SessionEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_end_time");

                    b.Property<string>("SessionName")
                        .HasColumnType("text")
                        .HasColumnName("session_name");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_start_time");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("FocusMapApi.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("ProfessionalLicense")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("professional_license");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfessionalId");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("FocusMapApi.Models.AudioDescriptionModel", b =>
                {
                    b.HasOne("FocusMapApi.Models.InterestPointModel", "InterestPoint")
                        .WithMany("AudioDescriptions")
                        .HasForeignKey("InterestPointId");

                    b.HasOne("FocusMapApi.Models.SessionModel", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestPoint");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FocusMapApi.Models.InterestPointModel", b =>
                {
                    b.HasOne("FocusMapApi.Models.UserModel", "Patient")
                        .WithMany("InterestPoints")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FocusMapApi.Models.SessionDataModel", b =>
                {
                    b.HasOne("FocusMapApi.Models.SessionModel", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FocusMapApi.Models.SessionModel", b =>
                {
                    b.HasOne("FocusMapApi.Models.UserModel", "Patient")
                        .WithMany("Sessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FocusMapApi.Models.UserModel", b =>
                {
                    b.HasOne("FocusMapApi.Models.UserModel", "Professional")
                        .WithMany("Patients")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("FocusMapApi.Models.InterestPointModel", b =>
                {
                    b.Navigation("AudioDescriptions");
                });

            modelBuilder.Entity("FocusMapApi.Models.UserModel", b =>
                {
                    b.Navigation("InterestPoints");

                    b.Navigation("Patients");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
